blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussion
    url: https://github.com/unlv-evol/unlv-evol/discussions
    about: Please use GitHub Discussions for general questions or research collaboration ideas.