name: doc-deploy 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated from v3

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated from v4
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v4  # Updated from v2
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('requirements.txt') }}
          path: .cache

      - name: Install dependencies
        run: |
          pip install mkdocs-material pillow cairosvg "mkdocstrings[python]"

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force